all:
		rm -f fenwick
		#gcc -o fenwick main.c src/fenwick-bit.c src/fenwick-bit.h src/fenwick-tree.c src/fenwick-tree.h
		gcc -o fenwick main.c src/fenwick-bit.c src/fenwick-bit.h src/avl-tree.c src/avl-tree.h

clean:
		rm -f fenwick
